#!/usr/bin/perl -w
# Data supplier - main script

use strict;
use warnings;
use File::Basename;
use File::Spec::Functions;

BEGIN {
	my $app_path = catdir(dirname($0), '..');
	my $config_path = catdir($app_path, 'lib', 'config');
	push @INC, $config_path;
	my $g = 'global_settings';
	require global_settings;
	require DataSupplierSettings;
	my $env_object = DataSupplierSettings->new;
}

use TestDataSupplier;

my $supplier = TestDataSupplier->new;
# Cleanup example: $env->register_for_cleanup($cmdline);

$supplier->execute();
