#!/bin/sh
# This is a MAS server startup/shutdown script for Debian GNU/Linux 
# (tested with version 3.0 - woody)
# mas-server depends on the following package: mailx
# To use without deb installation, do the following (as root):
# 1. Install MAS using the install script from the MAS tar distribution
# 2. Edit the three directories below to the values set during installation
#    The values below are Diebian defaults
# 3. Optionally edit other variables below
# 4. Create $MASDATA directory and populate with *.mas files with quotes
# 5. Copy this file to /etc/init.d/
# 6. Run: update-rc.d mas default

# Written and copyright (c) 2003 by Pawel Konieczny 
# (konieczp@users.sourceforge.net)
# Copyrighted under the Artistic License
# Debian users can find the license in /usr/share/common-licenses/Artistic
# Non-Debian users may view the license at
# http://www.opensource.org/licenses/artistic-license.php

MASDIR=/usr/local/bin
MASLIB=/usr/local/lib/mas
MASDOC=/usr/share/doc/mas
MASDATA=/var/lib/mas/stoxx
MASPORT=5050
MASOPTS='-o -f ,'
MASPID=/var/run/mas.pid

MAS_DIRECTORY=$MASLIB
MAS_MAILER=/usr/bin/mail
export MAS_DIRECTORY MAS_MAILER

test -f $MASDIR/mas || exit 0

case "$1" in

    start)
        # for some obscure reason, MAS does not start up well when using
        # start-stop-daemon
        if [ -f $MASPID ]; then
            echo "Not starting MAS server: already running."
        else
            echo -n "Starting MAS server: mas"
            cd $MASDATA
            su -p daemon "$MASDIR/mas $MASPORT $MASOPTS -b *.mas </dev/null >/dev/null 2>&1 &"
            if pidof -s $MASDIR/mas >$MASPID; then
                echo "."
            else
                rm -f $MASPID
                echo "...failed!"
                exit 2
            fi
        fi
        ;;

    stop)
        if [ ! -f $MASPID ]; then
            echo "Not stopping MAS server: none running."
        else
            echo -n "Stopping MAS server: mas"
            kill $(<$MASPID)
            rm -f $MASPID
            echo "."
        fi
        ;;

    restart|force-reload)
        echo -n "Restarting MAS server: mas... "
        if [ -f $MASPID ]; then
            kill $(<$MASPID)
        else
            killall --quiet $MASDIR/mas
            sleep 2
            killall --quiet --wait --signal KILL $MASDIR/mas
        fi
        cd $MASDATA
        sleep 1
        su -p daemon "$MASDIR/mas $MASPORT $MASOPTS -b *.mas </dev/null >/dev/null 2>&1 &"
        if pidof -s $MASDIR/mas >$MASPID; then
            echo "done."
        else
            rm -f $MASPID
            echo "failed!"
            exit 2
        fi
        ;;

    *)
        echo "Usage: /etc/init.d/mas {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

exit 0
