#!/usr/bin/env python
# Make a release of the Market Analysis System.

from string import *
from release_functions import *
from posixpath import dirname

from os import getcwd
import sys
libdir = dirname(sys.argv[0]) + '/../lib/make_release'
util = ReleaseUtilities(libdir)
util.check_settings()
map_file = open(libdir + '/release_file_map')
for line in map_file.readlines():
	files = split(line)
	if files[0][0] == '#':
		continue	# Skip comment.
	util.add_source_file(files[0])
	util.add_target_file(files[1])
	util.add_to_packages(files[0], files[1], files[2:])
map_file.close()
util.copy()
util.make_packages()
util.cleanup()
