#!/usr/bin/env python
# Preprocess trading signals from MAS.
# Currently updates the up and down watch lists from the new long-term
# signals and passes them on to the mailer.  Passes all other signals (such
# as up and down short-term signals) to the mailer without processing.
# NOTE: Expects the string specified by the global variable `long_term_string'
# to be in the subject line of the long-term trend signals.

import sys
from pmm_settings import *
from regex import match
import os
from utilities import contents
from pmm import *

long_term_string = "long-term"
def send_mail(msg, args):
	otherargs = ""
	subject = ""
	i = 0
	while i < len(args):
		if args[i] == subject_flag and len(args) > i + 1:
			i = i + 1
			subject = args[i]
		else:
			otherargs = otherargs + " " + args[i]
		i = i + 1
	if subject != "":
		mailcmd = \
			mailer + " " + subject_flag + " '" + subject + "' " + otherargs
	sysresult = os.system("echo '" + contents(msg) + "'|" + mailcmd)
	if sysresult != 0:
		print "Mail command with subject " + subject + " failed."
	return subject

longterm = 0
message = sys.stdin.readlines()
for i in range(1, len(sys.argv)):
	if sys.argv[i] == long_term_string:
		longterm = 1
subject = send_mail(message, sys.argv[1:])
longterm = match(".*long-term.*", subject) != -1
if longterm:
	signals = unique_signals(message)
	uptrend_file_path = list_file_directory + path_sep + uptrend_file_name
	downtrend_file_path = list_file_directory + path_sep + downtrend_file_name
	update_trend_lists(signals, uptrend_file_path, downtrend_file_path)
