#!/usr/bin/env python
# Preprocess trading signals from MAS.
# Currently updates the up and down watch lists from the new long-term
# signals and passes them on to the mailer.  Passes all other signals (such
# as up and down short-term signals) to the mailer without processing.
# NOTE: Expects the string specified by the global variable `long_term_string'
# to be in the subject line of the long-term trend signals.

import sys
from pmm_settings import *
from regex import match
import os
from utilities import contents
from pmm import *

Use_db_envname = 'MAS_DATA_IN_DB'

def send_mail(msg, args):
	otherargs = ""
	subject = ""
	i = 0
	while i < len(args):
		if args[i] == subject_flag and len(args) > i + 1:
			i = i + 1
			subject = args[i]
		else:
			otherargs = otherargs + " " + args[i]
		i = i + 1
	if subject != "":
		mailcmd = \
			mailer + " " + subject_flag + " '" + subject + "' " + otherargs
	sysresult = os.system("echo '" + contents(msg) + "'|" + mailcmd)
	if sysresult != 0:
		print "Mail command with subject " + subject + " failed."
	return subject

def use_database():
	result = 0
	try:
		if os.environ[Use_db_envname] != '': result = 1
	except:
		None
	return result

longterm = 0
message = sys.stdin.readlines()
subject = send_mail(message, sys.argv[1:])
longterm = match(long_term_string, subject) != -1
watch_flags = [uptrend_flag, downtrend_flag, sidelined_flag]
if longterm:
	signals = unique_signals(message)
	if not use_database():
		uptrend_file_path = list_file_directory + path_sep + uptrend_file_name
		downtrend_file_path = list_file_directory + \
			path_sep + downtrend_file_name
		sidelined_file_path = list_file_directory + \
			path_sep + sidelined_file_name
		update_trend_lists(signals, uptrend_file_path, downtrend_file_path,
			sidelined_file_path)
	else:
		db_update_trend_lists(signals, watch_flags)
