#!/bin/bash
#  Pre-process a formatted document into groff or html.

Progname=$(basename $0)

usage() {
	echo Usage: $Progname [options] [file ...] >&2
	echo "Options:"
	echo "   -x extension_name    include text marked with 'extension_name'"
	echo "   -l                   format list constructs"
	echo "   -h                   output as html"
	if [ "$1" = "x" ]; then exit 1;fi
}

if [ $# -lt 1 ]
then
	usage x
fi

files=
list=false
null_xname="__0@not_used0@__"
end_title="end_title"

while [ $# -gt 0 ]; do
	case $1 in
		-x) shift; if [ $# -lt 1 ]; then usage x;fi
			xname=$1; shift ;;
		-l*) list=TRUE; shift ;;
		-h*) html=TRUE; shift ;;
		*) files="$files $1"; shift ;;
	esac
done

if [ -z "$xname" ]; then xname="$null_xname";fi
has_title=FALSE
if [ ! -z "$files" ] && grep "%$end_title" $files >/dev/null; then
	has_title=TRUE
fi

awk 'BEGIN {
	TRUE = 1
	FALSE = 0
	FS = ""
	In_extended_section = FALSE
	if ("'$xname'" == "'$null_xname'") Extensions = FALSE
	else Extensions = TRUE
	if ("'$list'" == "TRUE") Dolist = TRUE		# format lists
	if (groff()) printf("%s\n%s\n%s\n", ".SA 0", ".S 11", ".ll 6.4i")
#	if (groff()) printf("%s\n", ".hy 0")		# hyphenation off
	if ("'$has_title'" == "TRUE") {	# Parse the title.
		x = 0
		while (getline) {
			if ($1 ~ /%title/) {
				main_title = $2
			}
			else if ($1 ~ /%'$end_title'/) {
				printheader(main_title, sub_title, x)
				break
			} else {
				sub_title[x + 1] = $0
				++x
			}
		}
	} else {
		if (groff()) print ".de TP\n.."
	}
}

/^$/ { next } # skip blank lines

/^#/ { next } # skip #comment...

html() && /\\fB/ {
	gsub(/\\fB/, "<B>")
	boldon = TRUE
}

html() && /\\fI/ {
	gsub(/\\fI/, "<I>")
	italon = TRUE
}

(html() && $0 ~ /http:\/\//) {
	fldcnt = split($0, line, " ")
	$0 = ""
	for (i = 1; i <= fldcnt; ++i) {
		if (line[i] ~ /http:\/\//) {
			no_space = TRUE
			urlname = line[i]
			sub(/http:\/\//, "", urlname)
			sub(/\/.*/, "", urlname)
			# An URL cannot end with a period, so assume that any periods at
			# the end of "addr" are not part of the URL - place them
			# after the URL tag.
			addr = line[i]
			append_str = ""
			if (line[i] ~ /\.$/) {
				append_str = addr
				# Remove all "."s at the end of "addr":
				sub(/\.*$/, "", addr)
				# Remove all characters from "append_str" except for
				# the "."s at the end.
				while (append_str !~ /^\.\.*$/) {
					# Remove any "."s at beginning of "append_str":
					sub(/^\.*/, "", append_str)
					# Remove all non-dot characters at beginning
					# of "append_str":
					sub(/^[^.]*/, "", append_str)
				}
			}
			$0 = $0 url(addr, urlname) append_str
		} else {
			if (i > 1 && ! no_space) {
				$0 = $0 " " line[i]
			} else {
				if (no_space) {
					$0 = $0 "\n" line[i]
					no_space = FALSE
				} else {
					$0 = $0 line[i]
				}
			}
		}
	}
}

html() && /\\fP/ {
	if (boldon) {
		gsub(/\\fP/, "</B>")
		boldon = FALSE
	} else if (italon) {
		gsub(/\\fP/, "</I>")
		italon = FALSE
	}
}

/^@begin/ {
	In_extended_section = TRUE
	Ignore_extended_section = TRUE
	fields = split($0, a, ":")
	if (fields > 1 && a[2] == "'$xname'") {
		Ignore_extended_section = FALSE
	}
}

/^@end/ {
	In_extended_section = FALSE
}

(In_extended_section) {
	if (Ignore_extended_section) {
		next
	}
}

/^@/ {
	# Lines starting with @ indicate an "extension"
	if (! Extensions) {
		# Skip the line because 'Extensions' are off.
		next
	} else if ($0 !~ "^@'$xname'") {
		# Skip because 'Extensions' are on and $0 does not match 'xname'.
		next
	}
}

/%date/ {
	date = $2
	next
}

/%hdg1/ {
	print_heading($2, 1)
	date = ""
	next
}

/%hdg2/ {
	print_heading($2, 2)
	date = ""
	next
}

/%br/ {
	if (groff()) print ".br"
	else print "<br>"
	next
}

/%startlist/ {
	if (Dolist) {
		if (groff()) {
			printf(".BL\n")
		} else {
			print "<P>\n<UL>"
		}
		++list_nesting
	}
	next
}

/%listitem/ {
	if (Dolist)
		if (groff()) {
			printf(".LI\n")
		} else {
			print "<LI>"
		}
	next
}

/%endlist/ {
	if (! Dolist) {
		next
	}
	if (list_nesting > 0) {
		if (groff()) {
			printf(".LE\n.P\n")
		} else {
			print "</UL>\n<P>"
		}
		--list_nesting
	} else {
		warncmd = "echo -e \"Warning: %endlist with no corresponding %startlist"
		warncmd = warncmd " (on line " NR ")\" >&2"
		system(warncmd)
	}
}

/%par/ {
	if (groff()) printf(".P\n")
	else print "<P>"
	next
}

(groff() && NR > 20 && ! newTP) {
	newTP = TRUE
	printf(".de TP\n.sp 0.5\n")
	printf(".tl '\''\\fBPage \\\\nP'\'''\''%s'\''\\fP\n", main_title)
	printf(".sp 3\n..\n")
}

/^@'$xname'/ {
	if (Extensions) print $2
	next
}

/^%/ {
	# Unrecognized key word - skip.
	next
}

{		# must be text, so print it
	print
}

function printheader(main, subt, sub_line_count) {
	if (groff()) {
		printf("%s\n%s\n", ".de TP", ".sp 1.25")
		if (main != "") {
			printf(".ce\n\\s+1\\fB%s\\s-1\n", main)
		}
		for (i = 1; i <= sub_line_count; ++i) {
			printf(".ce\n%s\n", subt[i])
		}
		printf("\\fP\n.sp 1.25\n..\n")
	} else {
		if (main == "" && sub_line_count == 0) {
			next
		}
		print "<TITLE>"
		if (main != "") {
			printf("%s -", main)
		}
		for (i = 1; i <= sub_line_count; ++i) {
			printf(" %s", subt[i])
		}
		print "\n</TITLE>"
	}
}

function print_heading(hdg, level) {
	if (groff()) {
		printf(".br\n.ne 7\n")
		if (level == 1) {
			font = "\\fB"
		} else if (level == 2) {
			font = "\\fI"
		} else {
			warn("Cannot handle level " level " - skipping heading.")
			return
		}
		printf(".P\n%s", font)
		if (DATEFIRST)
		{
			if (date)
				printf("%s, ", date)
			printf("%s\n", hdg)
		}
		else
		{
			printf("%s", hdg)
			if (date)
				printf(", %s", date)
			printf("\n")
		}
		printf("\\fP\n")
	} else {
		if (level == 1) {
			hlvl = 2
		} else if (level == 2) {
			hlvl = 3
		} else {
			warn("Cannot handle level " level " - skipping heading.")
			return
		}
		printf("<p>\n<h%d>\n%s\n</h%d>\n", hlvl, hdg, hlvl)
	}
}

function html() {
	result = 0
	if ("'$html'" == "TRUE") result = 1
	return result
}

function url(address, label) {
	return sprintf("<A href=\"%s\">\n%s</A>", address, label)
}

function groff() {
	return ! html()
}

function warn(s) {
	system("echo " s)
}
' $files
