#!/bin/bash
# Make a NetworkProtocol class for the TA server protocol.

eiffel_protocol_files ()
{
	echo ../../server1/network/gui_network_protocol.e \
		../../server1/network/network_protocol.e
}

proto_files=$(eiffel_protocol_files)
awk 'BEGIN {
	print "package common;\n"
	print "/** Constants specifying the components of the TA network \n\
communication protocol */"
	print "public interface NetworkProtocol\n{"
}

# Ignore deferred features.
/is  *\<deferred\>/ { next }

/^feature/ {
	sub (/.*-- */, "")
	print "\n\t// " $0
}
/: *INTEGER/ {
	sub (/:/, "")
	print "\tint " $1 " = " $4 ";"
}
/: *STRING/ {
	sub (/:/, "")
	# Change Eiffel tab char to java tab char.
	if ($4 == "\"%T\"") {
		value = "\"\\t\""
	}
	# Change Eiffel newline char to java newline char.
	else if ($4 == "\"%N\"") {
		value = "\"\\n\""
	}
	else {
		value = $4
	}
	print "\tString " $1 " = " value ";"
}
END {
	print "\n\t// Currently, only daily and weekly period types are supported."
	print "\tString daily_period_type = \"daily\";"
	print "\tString weekly_period_type = \"weekly\";"
	print "}"
}' $proto_files >../common/NetworkProtocol.java
