#!/usr/bin/env python
# Program Control Terminal
# This is a python script whose purpose is to control a set of related
# programs.  This script uses a configuration file to determine what
# programs are to be controlled and how to start and stop them.
# The configuration file is located in one of two ways:
# The environment variable PCT_CONFIG_FILE can be set to the absolute path
# of the configuration file.  If this variable is not set or if the
# specified file does not exist, a file named {name}_config, where {name}
# represents the file name of this script, is searched for in the
# directories specified in the PYTHONPATH environment variable.  The
# components of the variable are searched from left to right, and the
# first directory to contain a file of this name is used.  Since the
# default name of this script is pct, the default name of the configuration
# file is pct_config.  However, this can be changed by changing the name of
# this file.  For example, if you rename this file mct (standing for,
# perhaps, mail control terminal), a file named mct_config will be searched
# for as the congifuration file.

import os
import sys
import string

def program_name():
	l = string.split(sys.argv[0], os.sep)
	return l[len(l) - 1]

def abort(msg):
	print program_name() + ": ",
	if msg != None:
		print msg + " - ",
	print "Exiting ..."
	sys.exit(-1)

try:
	lastmodule = "ProgramControlTerminal";
	from ProgramControlTerminal import ProgramControlTerminal
except:
	abort("Failed to import library module " + lastmodule + ".\nHas " + \
		"PYTHONPATH been set to include the required python lib directory?")

def config_file_name():
	return program_name() + "_config"

try:
	pct = ProgramControlTerminal(config_file_name(), program_name())
	pct.execute()
except "", msg:
	abort(msg)
