#!/usr/bin/env python

from sys import *
from os import *
from socket import *
from math import *
from string import *

Buffersize = 1

def usage():
	print "Usage: " + argv[0] + " [-h hostname] port"

def as_number(s):
	result = 0
	digits = {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5,
				'6': 6, '7': 7, '8': 8, '9': 9}
	slen = len(s)
	for i in range(0, slen):
		result = result + digits[s[slen - i - 1]]  * pow(10, i)
	return int(result)

if len(argv) < 2:
	usage()
	exit(-1)

host = ""
argcount = len(argv)
i = 1
while i < argcount:
	if argv[i][:2] == '-h':
		if i + 1 < argcount:
			i = i + 1
			host = argv[i]
		else:
			usage(); exit(-1)
	else:
		try:
			port = eval(argv[i])
		except:
			usage(); exit(-1)
	i = i + 1

if host == "":
	f = popen("hostname")
	host = f.readline()[:-1]

s = socket(AF_INET, SOCK_STREAM)
message = []
s.connect(host, port)
s.send('C')
while 1:
	while 1:
		c = s.recv(Buffersize)
		if c == '' or c == '': break
		message.append(c)
	if c == '': break
	print join(message, ''),
	message = []
	response = stdin.readline()
	s.send(response)
s.close()
