#!/usr/bin/env python
# Market Analysis Command-Line (MACL) client - accesses the MA server
# command-line interface via a socket connection.

from sys import *
from os import *
from socket import *
from math import *
from string import *

Buffersize = 1

def usage():
	print "Usage: " + argv[0] + " [-h hostname] port"

if len(argv) < 2:
	usage()
	exit(-1)

host = ""
argcount = len(argv)
i = 1
while i < argcount:
	if argv[i][:2] == '-h':
		if i + 1 < argcount:
			i = i + 1
			host = argv[i]
		else:
			usage(); exit(-1)
	else:
		try:
			port = eval(argv[i])
		except:
			usage(); exit(-1)
	i = i + 1

if host == "":
	f = popen("hostname")
	host = f.readline()[:-1]

s = socket(AF_INET, SOCK_STREAM)
message = []
s.connect(host, port)
s.send('C')
while 1:
	while 1:
		c = s.recv(Buffersize)
		if c == '' or c == '': break
		message.append(c)
	if c == '': break
	print join(message, ''),
	message = []
	response = stdin.readline()
	s.send(response)
s.close()
